spring:
  servlet:
    multipart:
      # 上传一个文件最大值,默认1Mb
      max-file-size: 200MB
      # 上传多个文件最大值,50Mb,默认10Mb
      max-request-size: 500MB
debug: true
logging:
  level:
    com:
      giantan: DEBUG
  file: 'game-assist.log'